### ISSUE TITLE
Can't deploy.  Error: "toolkit stack must be deployed to the environment"

### ISSUE THREAD

**Issue by duzvik** [insanitybit/grapl#27]
Hello, thank for open-sourcing this project. Trying to "dive" in but can't finish the deployment.
deploy_all.sh gives error: 
```
❌  grapl-generic-subgraph-generator-stack failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")"   

```
What I'm missing?

**Comment by insanitybit** [comment]
Hi @duzvik , sorry about that - I'll try to help you get around that error.

You may need to run ```cdk bootstrap``` in the `grapl-cdk` directory.

If that doesn't work can you tell me your version of cdk?
```cdk --version```

Are you running the command on a system with an AWS profile configured with a region?

**Comment by insanitybit** [comment]
Also, and I've noted this in the README, the default configuration of Grapl may provision resources outside of AWS's free tier. It may amount of hundreds of dollars a month in charges (I'm working on cutting that down considerably).

If you play around with the system I suggest deleting the CloudFormation stacks when you're done to avoid being charged more than you expect.

**Comment by duzvik** [comment]
> You may need to run cdk bootstrap in the grapl-cdk directory.
This helped. thanks. Also I've run git pull.

But a new problem.  Seems engagementedgegrapl-stack is missing.
I've checked stack list in Cloudformation and engagementedgegrapl-stack is missing.
When I try to install it manually(no via deploy_all.sh)  with command: 
`cdk deploy -v --require-approval=never engagementedgegrapl-stack`

I got the following error:
`No stack found matching 'engagementedgegrapl-stack'. `

Here is verbose output:
> CDK toolkit version: 1.14.0 (build 261a1bf)
Command line arguments: { _: [ 'deploy' ],
  v: true,
  verbose: true,
  'require-approval': 'never',
  requireApproval: 'never',
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  '$0': '/usr/bin/cdk',
  STACKS: [ 'engagementedgegrapl-stack' ],
  stacks: [ 'engagementedgegrapl-stack' ] }
Determining whether we're on an EC2 instance.
Looks like EC2 instance.
cdk.json: {
  "app": "node index.js"
}
cdk.context.json: {
  "availability-zones:_REDACTED_:us-east-1": [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1d",
    "us-east-1e",
    "us-east-1f"
  ],
  "availability-zones:account=_REDACTED_:region=us-east-1": [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1d",
    "us-east-1e",
    "us-east-1f"
  ]
}
merged settings: { versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'node index.js',
  context: {},
  tags: [],
  assetMetadata: true,
  requireApproval: 'never',
  toolkitBucket: {},
  staging: true }
Setting "CDK_DEFAULT_REGION" environment variable to eu-west-1
Resolving default credentials
Retrieved account ID _REDACTED_ from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to _REDACTED_
context: { 'availability-zones:_REDACTED_:us-east-1':
   [ 'us-east-1a',
     'us-east-1b',
     'us-east-1c',
     'us-east-1d',
     'us-east-1e',
     'us-east-1f' ],
  'availability-zones:account=_REDACTED_:region=us-east-1':
   [ 'us-east-1a',
     'us-east-1b',
     'us-east-1c',
     'us-east-1d',
     'us-east-1e',
     'us-east-1f' ],
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true }
outdir: cdk.out
env: { CDK_DEFAULT_REGION: 'eu-west-1',
  CDK_DEFAULT_ACCOUNT: '_REDACTED_',
  CDK_CONTEXT_JSON:
   '{"availability-zones:_REDACTED_:us-east-1":["us-east-1a","us-east-1b","us-east-1c","us-east-1d","us-east-1e","us-east-1f"],"availability-zones:account=_REDACTED_:region=us-east-1":["us-east-1a","us-east-1b","us-east-1c","us-east-1d","us-east-1e","us-east-1f"],"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.10.0',
  CDK_CLI_VERSION: '1.14.0' }
/home/ubuntu/grapl/grapl-cdk/edge_ux/
{ sourceHash:
   '6416c21be320b522db64c705872c0a54d788e3df57b34a5f0d1e8602d7521430' }
Assertion failed: Could not find any integrations. Ensure you have deployed engagement edge.
No stack found matching 'engagementedgegrapl-stack'. Use "list" to print manifest
Error: No stack found matching 'engagementedgegrapl-stack'. Use "list" to print manifest
    at AppStacks.selectStacks (/usr/lib/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:150:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Here is list output:

> /home/ubuntu/grapl/grapl-cdk/edge_ux/
{ sourceHash:
   '6416c21be320b522db64c705872c0a54d788e3df57b34a5f0d1e8602d7521430' }
Assertion failed: Could not find any integrations. Ensure you have deployed engagement edge.
engagement-ux-stack
grapl-event-emitters-stack
grapl-user-auth-table-stack
graplhistorydb-stack
graplvpcs-stack
engagementedgeduzzz-grapl-stack
engagementgraphcluster-stack
engagements-notebook-stack
grapl-analyzer-dispatcher-stack
grapl-analyzer-executor-stack
grapl-engagement-creator-stack
grapl-generic-subgraph-generator-stack
grapl-graph-merger-stack
grapl-node-identifier-stack
grapl-node-identity-mapper-stack
grapl-sysmon-subgraph-generator-stack
mastergraphcluster-stack

**Comment by insanitybit** [comment]
I see the problem. I'll have a patch up soon.

It looks like the stack name is parameterized by your bucket prefix, which should not be the case. This is leading to a stack name of:

``` engagementedgeduzzz-grapl-stack```

Instead of ``` engagementedged-grapl-stack```

In the short term you can manually modify the `deploy_all.sh` to remove the `uzzz` from the stack name.

Sorry about that, and thank you for reporting these issues!

**Comment by insanitybit** [comment]
Happy to help - I'm sorry that you're running into issues.

The prefix was not supposed to be part of the stack name, so in the `deploy_all.sh` it should simply be removed from any stack names. The latest master will already do this correctly now.

Yes, unfortunately the S3 buckets and DynamoDB tables don't clean up after the stack is deleted This is to ensure that users don't accidentally lose important data, but it can be a pain to have to manually clean that out.

Right, yeah, the notebook is empty to start. You can run a terminal in the notebook though and do a git clone of this repo, and that'll include the graph provision notebook. I'll clarify this in the documentation - in the future the repo should just be there by default, but I haven't gotten around to there yet.

Sorry for the hiccups.

**Comment by insanitybit** [comment]
@duzvik 

I believe these issues are fixed in the latest master branch of Grapl. If you have any other issues at all please feel free to open another issue, or reach out to me via Grapl's slack channel.

Thanks for reporting these issues and helping me to make Grapl better!
