### ISSUE TITLE
Install Grapl on premise... Is it possible?

### ISSUE THREAD

**Issue by spark2k06** [insanitybit/grapl#39]
Is it possible to install Grapl on premise or is the use of AWS mandatory? I can't find a clear way to get an installation like that by checking the GitHub repository.

**Comment by insanitybit** [comment]
Hi @spark2k06,

Supporting on-prem is something I'd like to get to, but there's no way of doing so today. I may be able to support a local version in the future, built on top of localstack, but a fully on-prem version is a ways off.

**Comment by spark2k06** [comment]
Ok. Thanks for the information.

**Comment by insanitybit** [comment]
Sure thing.
